[package]
name = "file_alloc"
version = "0.1.0"
description = "跨平台、高性能、兼容性好的文件大小分配库"
edition = "2021"
authors = ["share121 <me@s121.top>"]
homepage = "https://github.com/share121/file_alloc"
repository = "https://github.com/share121/file_alloc"
license = "MIT"
keywords = ["file", "allocation", "preallocate", "cross-platform"]
categories = ["filesystem", "asynchronous", "os"]

[dependencies]
tokio = { version = "1.50.0", features = ["fs", "io-util", "rt"] }

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1.4", features = ["fs"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features =[
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
] }

[dev-dependencies]
tempfile = "3.27.0"
tokio = { version = "1.50.0", features = ["full"] }

[lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
# restriction = { level = "deny", priority = -1 }
multiple_crate_versions = "allow"
nursery = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
